name: just_audio
description: A feature-rich audio player for Flutter. Loop, clip and concatenate any sound from any source (asset/file/URL/stream) in a variety of audio formats with gapless playback.
version: 0.9.18
homepage: https://github.com/ryanheise/just_audio/tree/master/just_audio

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  # just_audio_platform_interface: ^4.0.0
  # just_audio_platform_interface:
  #   path: ../just_audio_platform_interface
  just_audio_platform_interface: 
    git: # https://github.com/ryanheise/just_audio/issues/97#issuecomment-1020736223
      url: git@github.com:ryanheise/just_audio.git
      ref: 735089f927d28230503b63c8fdd3887e5f62bee2
      path: just_audio_platform_interface
  # just_audio_web: ^0.4.2
  # just_audio_web:
  #   path: ../just_audio_web
  just_audio_web:
    git: # https://github.com/ryanheise/just_audio/issues/97#issuecomment-1020736223
      url: git@github.com:sadahry/just_audio.git
      ref: cf88f193bed9cc1a41573ca9be8eab25de211c9c
      path: just_audio_web
  audio_session: ^0.1.6+1
  rxdart: '>=0.26.0 <0.28.0'
  path: ^1.8.0
  path_provider: ^2.0.0
  async: ^2.5.0
  uuid: ^3.0.1
  crypto: ^3.0.0
  meta: ^1.3.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  plugin_platform_interface: ^2.0.0
  pedantic: ^1.10.0

flutter:
  plugin:
    platforms:
      android:
        package: com.ryanheise.just_audio
        pluginClass: JustAudioPlugin
      ios:
        pluginClass: JustAudioPlugin
      macos:
        pluginClass: JustAudioPlugin
      web:
        default_package: just_audio_web
